version: "3.9"
services:
  jenkins:
    image: windsekirun/jenkins-android-docker:1.1.4
    container_name: jenkins_android
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "/data/jenkins-android-docker:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
